server:
  port: 8080

spring:
  main:
    web-application-type: servlet

stats-server:
  url: http://stats-server:9090

logging:
  level:
    ru.practicum.ewm: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics